"""Interruption model update.

Revision ID: 1a895b7b2cab
Revises: 5f8743958d33
Create Date: 2023-12-04 12:40:32.684224

"""
from alembic import op
import sqlalchemy as sa

from datajournals import db
from datajournals.models import SleepInterruptionAssociation, SleepInterruptionTag

# revision identifiers, used by Alembic.
revision = '1a895b7b2cab'
down_revision = '5f8743958d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_interruptions')
    with op.batch_alter_table('sleep_interruption_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stop', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    iq = db.session.query(SleepInterruptionAssociation, SleepInterruptionAssociation.tag_id).all()
    for i, t in iq:
        i.tags.append(db.session.query(SleepInterruptionTag).filter_by(id=t).first())
        db.session.add(i)
        db.session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('sleep_interruption_association', schema=None) as batch_op:
        batch_op.drop_column('stop')
        batch_op.drop_column('start')

    op.create_table('sleep_interruptions',
                    sa.Column('record_id', sa.INTEGER(), nullable=True),
                    sa.Column('tag_id', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['record_id'], ['sleep_record.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['sleep_interruption_tag.id'], )
                    )
    # ### end Alembic commands ###
