"""UpdateSleep

Revision ID: 5f8743958d33
Revises: 
Create Date: 2023-10-06 09:21:42.488814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8743958d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.alter_column('time_start', new_column_name='time_retire')
        batch_op.add_column(
            column=sa.Column('time_start_sleep', sa.DateTime(), nullable=True),
            insert_after='time_start')
        batch_op.add_column(
            column=sa.Column('time_stop_sleep', sa.DateTime(), nullable=True),
            insert_after='time_start_sleep')
        batch_op.alter_column('time_stop', new_column_name='time_rise')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.alter_column('time_retire', new_column_name='time_start')
        batch_op.alter_column('time_rise', new_column_name='time_stop')
        batch_op.drop_column('time_stop_sleep')
        batch_op.drop_column('time_start_sleep')

    # ### end Alembic commands ###
