"""Removed deprecated sleepdb columns.

Revision ID: 8980095e9428
Revises: 1a895b7b2cab
Create Date: 2023-12-04 12:47:33.538724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8980095e9428'
down_revision = '1a895b7b2cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_interruption_association', schema=None) as batch_op:
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_column('interrupt_duration')
        batch_op.drop_column('recline_after')
        batch_op.drop_column('recline_before')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recline_before', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('recline_after', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('interrupt_duration', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('sleep_interruption_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'sleep_interruption_tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###
