"""Journaldb record model update.

Revision ID: eeb79108e7a1
Revises: af0f1eb2d74e
Create Date: 2024-01-30 09:38:18.107926

"""
from alembic import op
import sqlalchemy as sa

from datajournals import db, get_app
from datajournals.models import JournalDescriptorTag

# revision identifiers, used by Alembic.
revision = 'eeb79108e7a1'
down_revision = 'af0f1eb2d74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unfinished', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('watched', sa.Boolean(), nullable=True, server_default='0'))

    with get_app().app_context():
        ut = db.session.query(JournalDescriptorTag).filter_by(tag='unfinished').first()
        for r in ut.records:
            r.unfinished = True
        db.session.add(ut)
        wt = db.session.query(JournalDescriptorTag).filter_by(tag='to be revisited').first()
        if wt:
            for r in wt.records:
                r.watched = True
            db.session.add(wt)
        db.session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_record', schema=None) as batch_op:
        batch_op.drop_column('watched')
        batch_op.drop_column('unfinished')

    # ### end Alembic commands ###
